Repository wanted-pre-onboarding-09/wanted-codestates-project-9-3, pull requests merged in 2022-03, with the labels that each got.

#4 Feat: Add ButtonTab component
  src/components/ButtonTab.js
Labels: enhancement, UI

#5 [#2]feature: item component markup
  package.json
  src/App.js
  src/components/OptionsItem.js
Labels: enhancement, UI

#15 [#8]feature: counter component markup
  src/App.js
  src/components/Counter.js
  src/components/List.js
Labels: enhancement, UI

#18 Feat: Merge components
  src/App.js
  src/components/List.js
  src/components/SearchBar.js
Labels: enhancement, UI

#20 feat: option list implement
  src/App.js
  src/components/Setting.js
  src/index.js
  src/store/index.js
  src/store/settingSlice.js
Labels: enhancement

#23 Feature/22 design
  public/index.html
  src/App.js
  src/components/ButtonTab.js
  src/components/Counter.js
  src/components/List.js
  src/components/SearchBar.js
  src/components/Setting.js
Labels: enhancement, UI

#31 Feature/30 add option slice
  src/App.js
  src/store/index.js
  src/store/optionSlice.js
Labels: enhancement

#37 Feature/27 mutil selection
  src/App.js
  src/components/Counter.js
  src/components/List.js
  src/components/OptionsItem.js
  src/components/index.js
  src/store/optionSlice.js
Labels: enhancement

#39 Feature/25 control button tab
  src/components/ButtonTab.js
  src/store/optionSlice.js
Labels: enhancement

#49 Feature/43 list design
  src/components/ButtonTab.js
  src/components/Counter.js
  src/components/List.js
  src/components/OptionsItem.js
  src/components/SearchBar.js
  src/components/Setting.js
Labels: enhancement

#51 Feature/50 global style
  src/App.css
  src/GlobalStyle.js
  src/components/List.js
  src/index.js
Labels: enhancement

#55 [#45]feature: multi selection edge case
  src/components/List.js
  src/components/OptionsItem.js
  src/store/optionSlice.js
Labels: enhancement

#56 Refactor/52 move selected
  src/components/List.js
  src/components/OptionsItem.js
  src/components/SearchBar.js
  src/components/Setting.js
  src/components/Title.js
  src/store/optionSlice.js
Labels: enhancement

#58 Feature/57 button hover
  src/components/ButtonTab.js
  src/components/OptionsItem.js
Labels: UI

#62 Refactor/61 updated data
  src/store/optionSlice.js
Labels: enhancement
